name: emotioncapture
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - matplotlib
  - pandas
  - qt
  - pytorch==2.0.*
  - torchvision
  - umap-learn
  - opencv
  - av
  - albumentations
  - mmengine
  - mmdet
  - pip
  - pip:
      - mmdeploy-runtime
      - mmpose
